### ISSUE TITLE
Windows Support / Building

### ISSUE THREAD

**Issue by photex** [google/ced#4]
Howdy! Love the ideas here and would be interested to know about windows support or potential roadblocks to support.

**Comment by ctiller** [comment]
Hey!

There's a few things: firstly I'm starting to get set up to be able to do a
GUI version: I'm getting convinced that the increased control over
rendering will be useful.

That said, having a terminal based environment is important to me too: I
spend a good deal of time ssh'd into VMs for my real job.

So for a Windows port, we'd need to figure terminal vs GUI first (long term
both would be good). Probably getting the terminal version up is easiest
since there's just a couple of files.

Next up there's clang. I know support is better on Windows nowadays, but
that's all I know. Everything for C++ support is heavily based on clang and
I expect some work there.

There is a long tail of platform specific non UI code. Things like
subprocess execution (run.h, run.cc) spring to mind, but I expect it's
scattered over the codebase and will need some abstraction work to hide it
away.

Finally, there's Bazel and the dependency tree. I'm told Bazel is getting
to a good point now compiling on Windows, but I've never tried it myself.
At least some of the dependency tree will need work here.

**Comment by photex** [comment]
Thanks for the details.

Bazel on windows has been lovely with the latest release so I'd expect that not to be an issue.

Clang and LLVM in general have nice installers for windows with each release. Trick is finding it (registry? env var?) I'd suppose. I have no idea how to tune Bazel to use clang instead of msvc or mingw.

The rest I don't have much insight on for the time being.

For your GUI plans, will you be wanting to use native toolkits for each platform, or use Qt, Cef or Electron etc?

**Comment by ctiller** [comment]
For Linux I currently have a .config/ced.yaml file that can point to
wherever different clang versions are, so we might just replicate that.

For GUI, I'm hoping to use Skia as a rendering backend, and then some
lightweight platform specific framing around that - for now.

**Comment by photex** [comment]
TIL Skia. 👍 🔥 

If it's fine with you I may noodle around and make an attempt to get stuff to build, but likely not run. My curiosity is piqued.

**Comment by dougbinks** [comment]
An advantage of keeping the console approach is that it should work with Linux Subsystem on Windows.

For GUI, I am pretty fond of [dear ImGui](https://github.com/ocornut/imgui) these days, though I can understand why Skia might be of interest.
